import{a as g,i as c,S as f}from"./assets/vendor-CRCB-GUD.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const d of t.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();async function h(r,o=1,n=15){const e=`https://pixabay.com/api/?key=45999578-eb7202f1a65d28d69ebdccc58&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${n}`;try{const t=await g.get(e);if(t.status!==200)throw new Error("Network response was not ok");return t.data.hits}catch(t){throw console.error("Error fetching images:",t),t}}function b(r,o){if(!r||r.length===0){c.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3});return}const n=r.map(s=>`
        <li class="gallery-item">
          <a href="${s.largeImageURL}">
            <img src="${s.webformatURL}" alt="${s.tags}" width="360" height="152" />
          </a>
          <div class="gallery-item-info">
            <p class="stats"><b>Likes</b> ${s.likes}</p>
            <p class="stats"><b>Views</b> ${s.views}</p>
            <p class="stats"><b>Comments</b> ${s.comments}</p>
            <p class="stats"><b>Downloads</b> ${s.downloads}</p>
          </div>
        </li>
      `).join("");o.insertAdjacentHTML("beforeend",n)}function w(r){r.innerHTML=""}let L=new f(".gallery-list a",{}),u="",l=1;const p=15,E=document.getElementById("search-form"),y=document.getElementById("gallery"),a=document.getElementById("load-more"),i=document.getElementById("loader");async function m(){i.style.display="block",a.style.display="none";try{const r=await h(u,l,p);if(r.length===0&&l===1){c.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3}),i.style.display="none";return}b(r,y),L.refresh(),r.length===p?a.style.display="block":a.style.display="none",i.style.display="none",l+=1}catch(r){console.error("Error fetching images:",r),c.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight",timeout:5e3}),i.style.display="none"}}E.addEventListener("submit",function(r){r.preventDefault();const o=document.getElementById("search-input").value.trim();if(!o){c.error({message:"Please enter a search word."});return}o!==u&&(u=o,l=1,w(y)),a.style.display="none",m()});a.addEventListener("click",function(){m()});
//# sourceMappingURL=index.js.map
